# Generated by Django 5.0.1 on 2024-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
