# Generated by Django 5.0.1 on 2024-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_city_account_province_account_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=100, null=True),
        ),
    ]
