# Generated by Django 5.0.1 on 2024-03-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_passkey_reset'),
        ('account', '0004_account_status'),
    ]

    operations = [
    ]
