# Generated by Django 5.0.1 on 2024-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_0003_passkey_reset_0004_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='passkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
