# Generated by Django 5.0.1 on 2024-02-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField(blank=True, null=True)),
                ('date_latest_incident', models.DateTimeField(blank=True, null=True)),
                ('incomplete_date', models.BooleanField(default=False)),
                ('place_of_incident', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('description_of_evidence', models.TextField(blank=True, null=True)),
                ('service_information', models.CharField(blank=True, choices=[('crisis', 'Crisis Intervention Including Rescue'), ('issuance', 'Issuance / Enforcement of Barangay Protection Order')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perpetrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('identifying_marks', models.CharField(blank=True, max_length=250, null=True)),
                ('house_information', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('relationship_to_victim', models.CharField(blank=True, choices=[('currentSpouse', 'Current spouse / partner'), ('formerSpouse', 'Former spouse / partner'), ('currentFiance', 'Current fiance / dating relationship'), ('formerFiance', 'Former fiance / dating relationship'), ('employer', 'Employer / manager / supervisor'), ('agentOfEmployer', 'Agent of Employer'), ('teacher', 'Teacher / instructor / professor'), ('coach', 'Coach / trainer'), ('immediateFamily', 'Immediate family'), ('otherRelatives', 'Other relatives'), ('peopleOfAuthority', 'People of authority / service provider'), ('neighbors', 'Neighbors / peers / coworkers / classmates'), ('stranger', 'Stranger')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('live-in', 'Live-In'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('telephone_number', models.IntegerField(blank=True, null=True)),
                ('house_information', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence_files/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='case.case')),
            ],
        ),
    ]
