# Generated by Django 5.0.1 on 2024-02-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField(blank=True, null=True)),
                ('type_of_case', models.CharField(choices=[('Impacted', 'The Impacted Victim'), ('Behalf', 'Reporting on Behalf of Impacted Victim')], default='Pending', max_length=30)),
                ('service_information', models.CharField(blank=True, choices=[('crisis', 'Crisis Intervention Including Rescue'), ('issuance', 'Issuance / Enforcement of Barangay Protection Order')], max_length=20, null=True)),
                ('date_latest_incident', models.DateField(blank=True, null=True)),
                ('incomplete_date', models.BooleanField(default=False, null=True)),
                ('place_of_incident', models.CharField(blank=True, choices=[('house', 'House'), ('work', 'Work'), ('school', 'School'), ('commercialPlaces', 'Commercial Places'), ('religion', 'Religious Institutions'), ('placeOfMedicalTreatment', 'Place of Medical Treatment'), ('transport', 'Transport & Connecting Sites'), ('brothles', 'Brothels and Similar Establishments'), ('others', 'Others'), ('noResponse', 'No Response')], max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True)),
                ('description_of_evidence', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Close', 'Close')], default='Active', max_length=20)),
                ('status_description', models.TextField()),
                ('date_added', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.IntegerField(blank=True, default=0, null=True)),
                ('telephone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('region', models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True)),
                ('case_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='Perpetrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('identifying_marks', models.CharField(blank=True, max_length=250, null=True)),
                ('house_information', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True)),
                ('relationship_to_victim', models.CharField(blank=True, choices=[('currentSpouse', 'Current spouse / partner'), ('formerSpouse', 'Former spouse / partner'), ('currentFiance', 'Current fiance / dating relationship'), ('formerFiance', 'Former fiance / dating relationship'), ('employer', 'Employer / manager / supervisor'), ('agentOfEmployer', 'Agent of Employer'), ('teacher', 'Teacher / Instructor / Professor'), ('coach', 'Coach / trainer'), ('immediateFamily', 'Immediate family'), ('otherRelatives', 'Other Relatives'), ('peopleOfAuthority', 'People of authority / service provider'), ('neighbors', 'Neighbors / peers / coworkers / classmates'), ('stranger', 'Stranger')], max_length=30, null=True)),
                ('case_perpetrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perpetrator', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('live-in', 'Live-In'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=10, null=True)),
                ('type_of_disability', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.IntegerField(blank=True, default=0, null=True)),
                ('telephone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('house_information', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True)),
                ('case_victim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('live-in', 'Live-In'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.IntegerField(blank=True, default=0, null=True)),
                ('telephone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('house_information', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True)),
                ('victim_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='case.victim')),
            ],
        ),
    ]
