# Generated by Django 5.0.1 on 2024-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_person',
            name='bldg_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
