# Generated by Django 5.0.1 on 2024-02-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perpetrator',
            name='case_perpetrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perpetrator', to='case.case'),
        ),
        migrations.AddField(
            model_name='victim',
            name='case_victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='case.case'),
        ),
    ]
