# Generated by Django 5.0.1 on 2024-03-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_contact_person_bldg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='economic_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='emergency_shelter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='enforcement_of_protection_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='forensic_interview_and_investigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='healthcare_provider_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='case',
            name='issuance_of_medical_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='law_enforcement_agency_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='case',
            name='medico_legal_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='none_type_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='other_service_provider_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='case',
            name='provision_of_appropriate_medical_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='psychosocial_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='receipt_and_recording_of_complaints',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='refers_to_healthcare_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='refers_to_law_enforcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='refers_to_other_service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='refers_to_social_welfare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='rescue_operations_of_vaw_cases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_service',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='educational_attainment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='religion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='suffix',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='type_of_disability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='contact_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='educational_attainment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='religion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='type_of_disability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
