# Generated by Django 5.0.1 on 2024-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_parent_occupation_perpetrator_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perpetrator',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
