# Generated by Django 5.0.1 on 2024-02-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_date_latest_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='telephone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
