# Generated by Django 5.0.1 on 2024-03-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_case_economic_assistance_case_emergency_shelter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='none_type_of_service',
        ),
    ]
