# Generated by Django 5.0.1 on 2024-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_remove_case_none_type_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='relationship_to_victim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='ages_of_children',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='number_of_children',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
