# Generated by Django 5.0.1 on 2024-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_parent_religion_perpetrator_religion_victim_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perpetrator',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='perpetrator',
            name='telephone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
