# Generated by Django 5.0.1 on 2024-02-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_alter_victim_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='incomplete_date',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
