# Generated by Django 5.0.1 on 2024-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_alter_case_incomplete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='uploads/evidence_files/'),
        ),
    ]
