# Generated by Django 5.0.1 on 2024-03-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver_account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
