# Generated by Django 5.0.1 on 2024-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_perpetrator_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='type_of_disability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
