# Generated by Django 5.0.1 on 2024-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_alter_notification_receiver_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
