# Generated by Django 5.0.1 on 2024-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_alter_evidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='evidence_files/'),
        ),
    ]
