# Generated by Django 5.0.1 on 2024-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_parent_type_of_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
