# Generated by Django 5.0.1 on 2024-03-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_parent_perpetrator_relationship_of_guardian'),
        ('case', '0007_notification_read'),
    ]

    operations = [
    ]
