# Generated by Django 5.0.1 on 2024-03-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_merge_20240324_1839'),
        ('case', '0008_merge_20240324_2035'),
    ]

    operations = [
    ]
