# Generated by Django 5.0.1 on 2024-02-08 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_alter_evidence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_case',
            field=models.CharField(choices=[('Impacted', 'The Impacted Victim'), ('Behalf', 'Reporting on Behalf of Impacted Victim')], default='Pending', max_length=30),
        ),
    ]
