# Generated by Django 5.0.1 on 2024-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_alter_case_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='checkbox_economic_abuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_physical_abuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_psychological_abuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_ra_9262',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_sexual_abuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='others_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
