# Generated by Django 5.0.1 on 2024-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_case_checkbox_economic_abuse_case_checkbox_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='checkbox_ra_8353',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_rape_by_sexual_assault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_rape_by_sexual_intercourse',
            field=models.BooleanField(default=False),
        ),
    ]
