# Generated by Django 5.0.1 on 2024-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_case_checkbox_ra_8353_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='checkbox_acts_of_lasciviousness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_art_336',
            field=models.BooleanField(default=False),
        ),
    ]
