# Generated by Django 5.0.1 on 2024-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_person',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
