# Generated by Django 5.0.1 on 2024-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_case_checkbox_acts_of_lasciviousness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='checkbox_physical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_ra_7877',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_use_of_objects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_verbal',
            field=models.BooleanField(default=False),
        ),
    ]
