# Generated by Django 5.0.1 on 2024-02-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_contact_person_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='region',
            field=models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='region',
            field=models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='region',
            field=models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True),
        ),
    ]
