# Generated by Django 5.0.1 on 2024-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_alter_case_region_alter_contact_person_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='place_of_incident',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('work', 'Work'), ('school', 'School'), ('commercialPlaces', 'Commercial Places'), ('religion', 'Religious Institutions'), ('placeOfMedicalTreatment', 'Place of Medical Treatment'), ('transport', 'Transport & Connecting Sites'), ('brothles', 'Brothels and Similar Establishments'), ('others', 'Others'), ('noResponse', 'No Response')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perpetrator',
            name='relationship_to_victim',
            field=models.CharField(blank=True, choices=[('currentSpouse', 'Current spouse / partner'), ('formerSpouse', 'Former spouse / partner'), ('currentFiance', 'Current fiance / dating relationship'), ('formerFiance', 'Former fiance / dating relationship'), ('employer', 'Employer / manager / supervisor'), ('agentOfEmployer', 'Agent of Employer'), ('teacher', 'Teacher / Instructor / Professor'), ('coach', 'Coach / trainer'), ('immediateFamily', 'Immediate family'), ('otherRelatives', 'Other Relatives'), ('peopleOfAuthority', 'People of authority / service provider'), ('neighbors', 'Neighbors / peers / coworkers / classmates'), ('stranger', 'Stranger')], max_length=30, null=True),
        ),
    ]
