# Generated by Django 5.0.1 on 2024-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_case_checkbox_physical_case_checkbox_ra_7877_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='checkbox_a_7610',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_engage_prostitution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_ra_9775',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='checkbox_sexual_lascivious_conduct',
            field=models.BooleanField(default=False),
        ),
    ]
