# Generated by Django 5.0.1 on 2024-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_alter_case_place_of_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Close', 'Close')], default='Active', max_length=20),
        ),
    ]
