# Generated by Django 5.0.1 on 2024-02-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_case_checkbox_a_7610_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='description_of_evidence',
            new_name='description_of_incident',
        ),
    ]
