# Generated by Django 5.0.1 on 2024-02-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victim',
            name='type_of_disability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('live-in', 'Live-In'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.IntegerField(blank=True, default=0, null=True)),
                ('telephone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('house_information', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, choices=[('region-I', 'Region I – Ilocos Region'), ('region-II', 'Region II – Cagayan Valley'), ('region-III', 'Region III – Central Luzon'), ('region-IV', 'Region IV‑A – CALABARZON'), ('mimaropa', 'MIMAROPA Region'), ('region-V', 'Region V – Bicol Region'), ('region-VI', 'Region VI – Western Visayas'), ('region-VII', 'Region VII – Central Visayas'), ('region-VIII', 'Region VIII – Eastern Visayas'), ('region-IX', 'Region IX – Zamboanga Peninsula'), ('region-X', 'Region X – Northern Mindanao'), ('region-XI', 'Region XI – Davao Region'), ('region-XII', 'Region XII – SOCCSKSARGEN'), ('region-XIII', 'Region XIII – Caraga'), ('ncr', 'NCR – National Capital Region'), ('car', 'CAR – Cordillera Administrative Region'), ('barmm', 'BARMM – Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=250, null=True)),
                ('victim_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='case.victim')),
            ],
        ),
    ]
