# Generated by Django 5.0.1 on 2024-02-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_rename_description_of_evidence_case_description_of_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='victim_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='case.victim'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='case_victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
    ]
