# Generated by Django 5.0.1 on 2024-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_alter_case_date_latest_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='place_of_incident',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('work', 'Work'), ('school', 'School'), ('commercialPlaces', 'Commercial Places'), ('religion', 'Religious Institutions'), ('placeOfMedicalTreatment', 'Place of Medical Treatment'), ('transport', 'Transport & Connecting Sites'), ('brothles', 'Brothels and Similar Establishments'), ('others', 'Others'), ('noResponse', 'No Response')], max_length=150, null=True),
        ),
    ]
