# Generated by Django 5.0.1 on 2024-02-17 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0019_alter_case_region_alter_contact_person_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='victim_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='case.victim'),
        ),
    ]
