# Generated by Django 5.0.1 on 2024-02-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0021_perpetrator_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='educational_attainment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nationality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='religion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='type_of_disability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Parent_Perpetrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=150, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_attainment', models.CharField(blank=True, max_length=150, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_disability', models.CharField(blank=True, max_length=150, null=True)),
                ('nationality', models.CharField(blank=True, max_length=150, null=True)),
                ('religion', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('house_information', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('barangay', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('perpetrator_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_perp', to='case.perpetrator')),
            ],
        ),
    ]
