# Generated by Django 5.0.1 on 2024-02-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_alter_status_history_status_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
