# Generated by Django 5.0.1 on 2024-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0026_case_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='type_of_case',
            field=models.CharField(blank=True, default='Pending', max_length=30, null=True),
        ),
    ]
