# Generated by Django 5.0.1 on 2024-03-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0027_alter_case_type_of_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_history',
            name='status_date_added',
            field=models.DateField(),
        ),
    ]
