# Generated by Django 5.0.1 on 2024-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0028_alter_status_history_status_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_history',
            name='status_date_added',
            field=models.DateTimeField(),
        ),
    ]
