# Generated by Django 5.0.1 on 2024-03-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0030_witness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
